cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/add/(?P<drone_id>[0-9]+)/$', views.cart_add, name='cart_add'),
    path('remove/(?P<drone_id>[0-9]+)/$',
         views.cart_remove, name='cart_remove'),
]

mysite/urls.py

from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings
from rest_framework import routers
from mydrone import views

router = routers.DefaultRouter()
router.register(r'drones', views.DroneViewSet)
urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('mydrone.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    path('api/', include(router.urls)),
    path('orders/', include('orders.urls', namespace='orders')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]+static(settings.MEDIA_URL,
         document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views
app_name = 'orders'
urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddDroneForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    override = forms.BooleanField(required=False, widget=forms.HiddenInput)   

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from mydrone.models import Drone, Category
from .cart import Cart
from .forms import CartAddDroneForm
from django.contrib.auth.decorators import login_required
category_list = Category.objects.all()
@login_required
@require_POST
def cart_add(request, drone_id):
    cart = Cart(request)
    drone = get_object_or_404(Drone, id=drone_id)
    form = CartAddDroneForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(drone=drone,
                 quantity=cd['quantity'],
                 override_quantity=cd['override'])
    return redirect('cart:cart_detail')

@login_required
@require_POST
def cart_remove(request, drone_id):
    cart = Cart(request)
    drone = get_object_or_404(Drone, id=drone_id)
    cart.remove(drone)
    return redirect('cart:cart_detail')

@login_required
def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddDroneForm(initial={'quantity': item['quantity'],
                                                                   'override': True})
    username = request.session.get('username', 0)                                                               
    return render(request, 'cart/detail.html', {'cart': cart, 
                                                'username': username,
                                                'categories': category_list})

cart/templates/cart/detail.html
{% extends "store/index.html" %}
{% load static %}
{% block content %}
<!-- Header Inner -->

<!--/ End Header -->


<!-- Shopping Cart -->
<div class="shopping-cart section">
	<div class="container">
		<div class="row">
			<div class="col-12">
				<!-- Shopping Summery -->
				<table class="table shopping-summery">
					<thead>
						<tr class="main-hading">
							<th>SẢN PHẨM</th>
							<th>TÊN</th>
							<th class="text-center">ĐƠN GIÁ (đ)</th>
							<th class="text-center">SỐ LƯỢNG</th>
							<th class="text-center">THÀNH TIỀN</th>
							<th class="text-center"><i class="ti-trash remove-icon"></i></th>
						</tr>
					</thead>
					<tbody>
						{% for item in cart %}
						{% with drone=item.drone %}
						<tr>
							<td class="image" data-title="No"><img src="{{drone.image.url}}" alt="{{drone.name}}">
							</td>
							<td class="drone-des" data-title="Description">
								<p class="drone-name"><a
										href="{% url 'store:drone.html' drone.pk %}">{{drone.name}}</a></p>
							</td>
							<td class="price" data-title="Price"><span>{% load humanize %}{{drone.price|floatformat:0|intcomma}}</span></td>
							<td class="qty" data-title="Qty">
								<!-- Input Order -->
								<div class="input-group">
									<form action="{% url 'cart:cart_add' drone.id %}" method="POST">
										{{item.update_quantity_form.quantity}}
										{{item.update_quantity_form.override}}
										{% csrf_token %}
										<input type="submit" value="&#x21bb;">
									</form>
								</div>
								<!--/ End Input Order -->
							</td>
							<td class="total-amount" data-title="Total"><span>{% load humanize %}{{item.total_price|floatformat:0|intcomma}}</span></td>
							<td class="action" data-title="Remove">
								<form action="{% url 'cart:cart_remove' drone.id %}" method="POST">
									{% csrf_token %}
									<input type="submit" value="&#9746;">
								</form>
							</td>							
						</tr>
						{% endwith %}
						{% endfor %}
					</tbody>
				</table>
				<!--/ End Shopping Summery -->
			</div>
		</div>
		<div class="row">
			<div class="col-12">
				<!-- Total Amount -->
				<div class="total-amount">
					<div class="row">
						<div class="col-lg-8 col-md-5 col-12">

						</div>
						<div class="col-lg-4 col-md-7 col-12">
							<div class="right">
								<ul>
									<li>Tạm tính<span>{% load humanize %}{{cart.get_total_price|floatformat:0|intcomma}}
											đ</span></li>
									<li>Giao hàng<span>Miễn phí</span></li>
									<li>Tiết kiệm<span>0 đ</span></li>
									<li class="last">Tổng đơn hàng<span>{% load humanize %}{{cart.get_total_price|floatformat:0|intcomma}} đ</span></li>
								</ul>
								<div class="button5">
									{% if cart%}
									<a href="{% url 'orders:order_create' %}" class="btn">Đặt hàng</a>
									{% endif %}
									<a href="{% url 'store:shop.html' 0 %}" class="btn">Tiếp tục chọn hàng</a>
								</div>
							</div>
						</div>
					</div>
				</div>
				<!--/ End Total Amount -->
			</div>
		</div>
	</div>
</div>
<!--/ End Shopping Cart -->
{% endblock content %}